apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-grpc
  name: notification-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-grpc
  strategy: {}
  template:
    metadata:
      labels:
        app: notification-grpc
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: https://+
        - name: ConnectionStrings__ClassifiedAds
          value: Server=db;Database=ClassifiedAds.Microservices;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true
        - name: MessageBroker__Provider
          value: RabbitMQ
        - name: MessageBroker__RabbitMQ__HostName
          value: rabbitmq
        envFrom:
        - configMapRef:
            name: shared
        image: phongnguyend/classifiedads.services.notification.grpc
        name: notification-grpc
        resources: {}
      restartPolicy: Always
status: {}
