apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-background
  name: notification-background
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-background
  strategy: {}
  template:
    metadata:
      labels:
        app: notification-background
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__ClassifiedAds
          value: Server=db;Database=ClassifiedAds.Microservices;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true
        - name: IdentityServerAuthentication__Authority
          value: http://20.43.159.181
        - name: IdentityServerAuthentication__RequireHttpsMetadata
          value: "false"
        - name: MessageBroker__Provider
          value: RabbitMQ
        - name: MessageBroker__RabbitMQ__HostName
          value: rabbitmq
        - name: Notification__Email__Provider
          value: SmtpClient
        - name: Notification__Email__SmtpClient__Host
          value: mailhog
        - name: Notification__Email__SmtpClient__Port
          value: "1025"
        - name: Notification__Sms__Provider
          value: Fake
        - name: Notification__Sms__Twilio__AccountSId
        - name: Notification__Sms__Twilio__AuthToken
        - name: Notification__Sms__Twilio__FromNumber
        - name: Services__AuditLog__Grpc
          value: https://auditlog-grpc
        - name: Services__Identity__Grpc
          value: https://identity-grpc
        - name: Services__Notification__Grpc
          value: https://notification-grpc
        image: phongnguyend/classifiedads.services.notification.background
        name: notification-background
        resources: {}
      restartPolicy: Always
status: {}
