apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: product-api
  name: product-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  strategy: {}
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__ClassifiedAds
          value: Server=db;Database=ClassifiedAds.Microservices;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true
        envFrom:
        - configMapRef:
            name: shared
        image: phongnguyend/classifiedads.services.product.api
        name: product-api
        resources: {}
      restartPolicy: Always
status: {}
