apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: storage-api
  name: storage-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-api
  strategy: {}
  template:
    metadata:
      labels:
        app: storage-api
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__ClassifiedAds
          value: Server=db;Database=ClassifiedAds.Microservices;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true
        - name: IdentityServerAuthentication__Authority
          value: http://20.43.159.181
        - name: IdentityServerAuthentication__RequireHttpsMetadata
          value: "false"
        - name: MessageBroker__Provider
          value: RabbitMQ
        - name: MessageBroker__RabbitMQ__HostName
          value: rabbitmq
        - name: Services__AuditLog__Grpc
          value: https://auditlog-grpc
        - name: Services__Identity__Grpc
          value: https://identity-grpc
        - name: Services__Notification__Grpc
          value: https://notification-grpc
        - name: Storage__Local__Path
          value: /files
        - name: Storage__Provider
          value: Fake
        image: phongnguyend/classifiedads.services.storage.api
        name: storage-api
        resources: {}
      restartPolicy: Always
status: {}
