apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapi
  name: webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  strategy: {}
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__ClassifiedAds
          value: Server=db;Database=ClassifiedAds.ModularMonolith;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true
        - name: IdentityServerAuthentication__Authority
          value: http://20.43.162.56
        - name: IdentityServerAuthentication__RequireHttpsMetadata
          value: "false"
        - name: MessageBroker__Provider
          value: RabbitMQ
        - name: MessageBroker__RabbitMQ__HostName
          value: rabbitmq
        - name: Storage__Provider
          value: Fake
        image: phongnguyend/classifiedads.modularmonolith.webapi
        name: webapi
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
