apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: identityserver
  name: identityserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identityserver
  strategy: {}
  template:
    metadata:
      labels:
        app: identityserver
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__ClassifiedAds
          value: Server=db;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true
        - name: CookiePolicyOptions__IsEnabled
          value: "true"
        - name: CookiePolicyOptions__MinimumSameSitePolicy
          value: Lax
        - name: CookiePolicyOptions__Secure
          value: None
        - name: MessageBroker__AzureQueue__ConnectionString
          value: DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx;EndpointSuffix=core.windows.net
        - name: MessageBroker__Provider
          value: RabbitMQ
        - name: MessageBroker__RabbitMQ__HostName
          value: rabbitmq
        image: phongnguyend/classifiedads.identityserver
        name: identityserver
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
