apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webmvc
  name: webmvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webmvc
  strategy: {}
  template:
    metadata:
      labels:
        app: webmvc
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: BackgroundServer__Endpoint
          value: http://backgroundserver
        - name: CheckDependency__Enabled
          value: "true"
        - name: CheckDependency__Host
          value: migrator:80
        - name: ConnectionStrings__ClassifiedAds
          value: Server=db;Database=ClassifiedAds;User Id=sa;Password=sqladmin123!@#;MultipleActiveResultSets=true
        - name: CookiePolicyOptions__IsEnabled
          value: "true"
        - name: CookiePolicyOptions__MinimumSameSitePolicy
          value: Lax
        - name: CookiePolicyOptions__Secure
          value: None
        - name: CurrentUrl
          value: http://host.docker.internal:9003
        - name: MessageBroker__AzureQueue__ConnectionString
          value: DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx;EndpointSuffix=core.windows.net
        - name: MessageBroker__Kafka__BootstrapServers
          value: kafka:9092
        - name: MessageBroker__Provider
          value: RabbitMQ
        - name: MessageBroker__RabbitMQ__HostName
          value: rabbitmq
        - name: NotificationServer__Endpoint
          value: http://notificationserver
        - name: NotificationServer__PublicEndpoint
          value: http://localhost:9001
        - name: OpenIdConnect__Authority
          value: http://host.docker.internal:9000
        - name: OpenIdConnect__RequireHttpsMetadata
          value: "false"
        - name: ResourceServer__Endpoint
          value: http://webapi
        - name: ResourceServer__PublicEndpoint
          value: http://host.docker.internal:9002
        - name: Storage__Amazon__AccessKeyID
          value: xxx
        - name: Storage__Amazon__BucketName
          value: classifiedadds
        - name: Storage__Amazon__RegionEndpoint
          value: ap-southeast-1
        - name: Storage__Amazon__SecretAccessKey
          value: xxx
        - name: Storage__Azure__ConnectionString
          value: DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx;EndpointSuffix=core.windows.net
        - name: Storage__Azure__Container
          value: classifiedadds
        - name: Storage__Local__Path
          value: /files
        - name: Storage__Provider
          value: Local
        image: phongnguyend/classifiedads.webmvc
        name: webmvc
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
